default-catalog: local

catalog:
  local: 
    uri: http://192.168.0.27:8181
    s3.endpoint: http://192.168.0.27:9000
    py-io_impl: pyiceberg.io.pyarrow.PyArrowFileIO
    aws_access_key_id: admin
    aws_secret_access_key: iceberg123
  #  io_impl: org.apache.iceberg.aws.s3.S3FileIO
